"""StoryReview linking table model for PrismQ Database.

This module implements the StoryReview linking table that allows one Story 
to have multiple reviews with different types:
- grammar: Grammar and spelling review
- tone: Tone and voice consistency
- content: Content quality and accuracy
- consistency: Internal consistency check
- editing: Editorial improvements

Schema:
    StoryReview (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        story_id INTEGER NOT NULL REFERENCES Story(id),
        review_id INTEGER NOT NULL REFERENCES Review(id),
        version INTEGER NOT NULL CHECK (version >= 0),
        review_type TEXT NOT NULL CHECK (review_type IN 
            ('grammar', 'tone', 'content', 'consistency', 'editing')),
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE(story_id, version, review_type)
    )
    
    -- Performance indexes
    CREATE INDEX idx_storyreview_story_id ON StoryReview(story_id);
    CREATE INDEX idx_storyreview_review_id ON StoryReview(review_id);
    CREATE INDEX idx_storyreview_story_version ON StoryReview(story_id, version);

Implements:
    IModel[int] - Full persistence operations interface
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional

from T.Database.models.base import IModel


class ReviewType(str, Enum):
    """Types of Story reviews.
    
    Each type represents a different aspect of story review:
    - GRAMMAR: Grammar and spelling review
    - TONE: Tone and voice consistency
    - CONTENT: Content quality and accuracy
    - CONSISTENCY: Internal consistency check
    - EDITING: Editorial improvements
    """
    GRAMMAR = "grammar"
    TONE = "tone"
    CONTENT = "content"
    CONSISTENCY = "consistency"
    EDITING = "editing"


@dataclass
class StoryReviewModel(IModel[int]):
    """StoryReview linking table model for database operations.
    
    This model represents the many-to-many relationship between Story and Review,
    with additional metadata (version, review_type). Implements IModel[int] for
    full persistence operations.
    
    Attributes:
        id: Primary key (auto-generated by database)
        story_id: Foreign key to Story table
        review_id: Foreign key to Review table
        version: Story version being reviewed (INTEGER >= 0, UINT simulation)
        review_type: Type of review (grammar, tone, content, consistency, editing)
        created_at: Timestamp of creation
    
    Constraints:
        - version must be >= 0 (simulates unsigned integer)
        - review_type must be one of: grammar, tone, content, consistency, editing
        - UNIQUE(story_id, version, review_type) prevents duplicate reviews of 
          the same type for the same version
    
    Implements:
        IModel[int] - get_id(), exists(), get_created_at(), save(), refresh()
    
    Example:
        >>> story_review = StoryReviewModel(
        ...     story_id=1,
        ...     review_id=5,
        ...     version=2,
        ...     review_type=ReviewType.GRAMMAR
        ... )
        >>> print(f"Story {story_review.story_id} review type: {story_review.review_type.value}")
        Story 1 review type: grammar
    """
    
    story_id: int
    review_id: int
    version: int
    review_type: ReviewType
    id: Optional[int] = None
    created_at: datetime = field(default_factory=datetime.now)
    
    def __post_init__(self):
        """Validate version and convert review_type if needed.
        
        Raises:
            ValueError: If version is negative (must be >= 0 for UINT simulation)
        """
        if self.version < 0:
            raise ValueError(f"Version must be >= 0, got {self.version}")
        
        # Convert string to enum if needed
        if isinstance(self.review_type, str):
            self.review_type = ReviewType(self.review_type)
    
    # === IModel Interface Implementation ===
    
    def get_id(self) -> Optional[int]:
        """Return the unique identifier of this model.
        
        Returns:
            The ID if persisted, None otherwise.
        """
        return self.id
    
    def exists(self) -> bool:
        """Check if the model exists in the database.
        
        Returns:
            True if the model has an ID (has been saved), False otherwise.
        """
        return self.id is not None
    
    def get_created_at(self) -> Optional[datetime]:
        """Return the creation timestamp of this model.
        
        Returns:
            The creation timestamp.
        """
        return self.created_at
    
    def save(self) -> bool:
        """Persist the model to the database.
        
        Note: Actual persistence is handled by StoryReviewRepository.
        This method returns True to indicate the model is ready to be saved.
        
        Returns:
            True (persistence delegated to repository)
        """
        return True
    
    def refresh(self) -> bool:
        """Reload the model's data from the database.
        
        Note: Actual refresh is handled by StoryReviewRepository.
        
        Returns:
            True if model exists, False otherwise.
        """
        return self.exists()
    
    def to_dict(self) -> dict:
        """Convert to dictionary for database storage.
        
        Returns:
            Dictionary with all model fields serialized for storage.
            review_type is converted to string value.
            created_at is converted to ISO format string.
        """
        return {
            "id": self.id,
            "story_id": self.story_id,
            "review_id": self.review_id,
            "version": self.version,
            "review_type": self.review_type.value,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> "StoryReviewModel":
        """Create StoryReviewModel from dictionary.
        
        Args:
            data: Dictionary containing model fields. Required keys:
                  story_id, review_id, version, review_type.
                  Optional keys: id, created_at.
        
        Returns:
            New StoryReviewModel instance.
        """
        created_at = data.get("created_at")
        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)
        
        review_type = data["review_type"]
        if isinstance(review_type, str):
            review_type = ReviewType(review_type)
        
        return cls(
            id=data.get("id"),
            story_id=data["story_id"],
            review_id=data["review_id"],
            version=data["version"],
            review_type=review_type,
            created_at=created_at or datetime.now(),
        )
    
    @classmethod
    def get_sql_schema(cls) -> str:
        """Get the SQL CREATE TABLE statement for this model.
        
        Returns:
            SQL statement to create the StoryReview table with all
            constraints (CHECK, UNIQUE, FOREIGN KEY) and performance indexes.
        
        Note:
            The review_type CHECK constraint is generated dynamically from
            the ReviewType enum to maintain consistency.
        """
        # Generate CHECK constraint values from enum
        review_type_values = ", ".join(f"'{rt.value}'" for rt in ReviewType)
        
        return f"""
        CREATE TABLE IF NOT EXISTS StoryReview (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            story_id INTEGER NOT NULL,
            review_id INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK (version >= 0),
            review_type TEXT NOT NULL CHECK (review_type IN ({review_type_values})),
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            FOREIGN KEY (story_id) REFERENCES Story(id),
            FOREIGN KEY (review_id) REFERENCES Review(id),
            UNIQUE(story_id, version, review_type)
        );
        
        -- Performance indexes for common query patterns
        CREATE INDEX IF NOT EXISTS idx_storyreview_story_id ON StoryReview(story_id);
        CREATE INDEX IF NOT EXISTS idx_storyreview_review_id ON StoryReview(review_id);
        CREATE INDEX IF NOT EXISTS idx_storyreview_story_version ON StoryReview(story_id, version);
        """
